# Тема “Вычисления с помощью Numpy”

#### Задача 1

In [65]:
import numpy as np

In [66]:
a = np.array([[1, 2, 3, 3, 1],
              [6, 8, 11, 10, 7]])
a

array([[ 1,  2,  3,  3,  1],
       [ 6,  8, 11, 10,  7]])

In [67]:
a = np.transpose(a)
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [68]:
mean_a = np.mean(a, axis = 0)
mean_a

array([2. , 8.4])

#### Задача 2

In [69]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

#### Задача 3

In [70]:
a_1 = a_centered[0:5,0:1].copy()
a_1

array([[-1.],
       [ 0.],
       [ 1.],
       [ 1.],
       [-1.]])

In [71]:
a_2 = a_centered[0:5,1:].copy()
a_2

array([[-2.4],
       [-0.4],
       [ 2.6],
       [ 1.6],
       [-1.4]])

In [72]:
a_1 = np.transpose(a_1)
a_1

array([[-1.,  0.,  1.,  1., -1.]])

In [73]:
a_centered_sp = np.dot(a_1, a_2)
a_centered_sp

array([[8.]])

In [74]:
N = len(a_2)
N

5

In [75]:
S = a_centered_sp / (N-1)
S

array([[2.]])

#### Задача 4

In [76]:
a_cov = np.cov(np.transpose(a))
a_cov

array([[1. , 2. ],
       [2. , 4.3]])

In [77]:
cov = a_cov[0,1]
cov

2.0